name: Code Quality Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  quality-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Validate Gradle wrapper
        run: ./gradlew wrapper --gradle-version 8.14

      - name: Download dependencies
        run: ./gradlew dependencies --refresh-dependencies

      - name: Compile and check for syntax errors
        run: ./gradlew compileJava compileTestJava

      - name: Run tests
        run: ./gradlew test

      - name: Build project (final validation)
        run: ./gradlew build

      - name: Verify mod structure
        run: |
          echo "Checking if fabric.mod.json exists..."
          ls -la src/main/resources/fabric.mod.json
          echo "Checking if mod jar was created..."
          ls -la build/libs/
