name: Mod Build

on:
  workflow_dispatch:
    inputs:
      branches:
        description: 'Branches to build (comma-separated, e.g., main,1.20.1,1.21.4)'
        required: true
        default: 'main'
        type: string

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Set matrix
        id: set-matrix
        run: |
          # Convert comma-separated branches to JSON array
          branches="${{ github.event.inputs.branches }}"
          # Remove spaces and convert to JSON array
          branches_clean=$(echo "$branches" | tr -d ' ')
          # Convert to JSON array format
          json_array=$(echo "$branches_clean" | sed 's/,/","/g' | sed 's/^/"/' | sed 's/$/"/' | sed 's/^/[/' | sed 's/$/]/')
          echo "matrix=$json_array" >> $GITHUB_OUTPUT
          echo "Branches to build: $json_array"

  build:
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch: ${{ fromJson(needs.prepare.outputs.matrix) }}
      fail-fast: false

    steps:
      - name: Checkout specific branch
        uses: actions/checkout@v4
        with:
          ref: ${{ matrix.branch }}

      - name: Build
        uses: Ruochenfu2011/compilation@v1

      - name: Archive built .jar
        uses: actions/upload-artifact@v4
        with:
          name: Build-${{ matrix.branch }}
          path: ./build/libs