name: Mod Build

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Build
        uses: Ruochenfu2011/compilation@v1

      - name: Archive built .jar
        uses: actions/upload-artifact@v2
        with:
          name: Build
          path: ./build/libs